####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VHD_SRC_LIST = ${PWD}/../samples/${AFU}/hw/vhdl_files.list 

DUT_VLOG_SRC_LIST = ${PWD}/../samples/${AFU}/hw/vlog_files.list 

DUT_INCDIR = ${PWD}/../samples/${AFU}/hw/+${PWD}/../samples/${AFU}/hw/par

ASEHW_FILE_LIST = \
	${PWD}/hw/ase_pkg.sv \
	${PWD}/hw/ccip_if_pkg.sv \
	${PWD}/hw/ccip_emulator.sv \
	${PWD}/hw/ase_top.sv \
	${PWD}/hw/outoforder_wrf_channel.sv \
	${PWD}/hw/ccip_logger.sv \
	${PWD}/hw/latency_pipe.sv \
	${PWD}/hw/ccip_sniffer.sv \
	${PWD}/hw/ase_svfifo.sv \


ASE_INCDIR = ${PWD}/hw/+

ASESW_FILE_LIST = \
	${PWD}/sw/linked_list_ops.c \
	${PWD}/sw/ipc_mgmt_ops.c \
	${PWD}/sw/mem_model.c \
	${PWD}/sw/randomness_control.c \
	${PWD}/sw/tstamp_ops.c \
	${PWD}/sw/error_report.c \
	${PWD}/sw/protocol_backend.c \
	${PWD}/sw/mqueue_ops.c \
	${PWD}/sw/ase_ops.c \


ASE_TOP = ase_top

SIMULATOR ?= QUESTA

