####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VHD_SRC_LIST = ${PWD}/../${AFU}/hw/vhdl_files.list 

DUT_VLOG_SRC_LIST = ${PWD}/../${AFU}/hw/vlog_files.list 

DUT_INCDIR = ${PWD}/../${AFU}/hw/+${PWD}/../${AFU}/hw/par+${PWD}/../${AFU}/hw/QSYS_IPs+${PWD}/../${AFU}/hw/QSYS_IPs/RAM+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/ram_2port_160+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/ram_2port_160/sim+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/ram_2port_160/synth+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/synopsys+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/synopsys/vcs+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/synopsys/vcsmx+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/mentor+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/aldec+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/cadence+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/sim/cadence/cds_libs+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/synth+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/ram_2port_160+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/ram_2port_160/sim+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/ram_2port_160/synth+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/synopsys+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/synopsys/vcs+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/synopsys/vcsmx+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/mentor+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/aldec+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/cadence+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/sim/cadence/cds_libs+${PWD}/../${AFU}/hw/QSYS_IPs/RAM/req_C1TxRAM2PORT/synth+${PWD}/../${AFU}/hw/include_files+${PWD}/../${AFU}/hw/include_files/common+

ASEHW_FILE_LIST = \
	${PWD}/hw/ase_pkg.sv \
	${PWD}/hw/ccip_if_pkg.sv \
	${PWD}/hw/ccip_emulator.sv \
	${PWD}/hw/ase_top.sv \
	${PWD}/hw/outoforder_wrf_channel.sv \
	${PWD}/hw/ccip_logger.sv \
	${PWD}/hw/latency_pipe.sv \
	${PWD}/hw/ccip_sniffer.sv \
	${PWD}/hw/ase_svfifo.sv \


ASE_INCDIR = ${PWD}/hw/+

ASESW_FILE_LIST = \
	${PWD}/sw/linked_list_ops.c \
	${PWD}/sw/ipc_mgmt_ops.c \
	${PWD}/sw/mem_model.c \
	${PWD}/sw/randomness_control.c \
	${PWD}/sw/tstamp_ops.c \
	${PWD}/sw/error_report.c \
	${PWD}/sw/protocol_backend.c \
	${PWD}/sw/mqueue_ops.c \
	${PWD}/sw/ase_ops.c \


ASE_TOP = ase_top

SIMULATOR ?= QUESTA

